### ISSUE TITLE
i get error message "Index out of range."

### ISSUE THREAD

**Issue by mrMuppet** [HosseinShams00/AdobeConnectDownloader#11]
``Start of process works: 
- Extract ZIP Data gets green
- Get Streams Data gets green
- Download Assets gets green

During this there are some files downloaded and two XML- and a lot of small flv-files extracted. 
Then i get the following message with "go on" or "cancel" : 
```
Index out of range. Must be non-negative and less than the size of the collection. (Parameter 'index'). 

System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at AdobeConnectDownloader.Application.AudioManager.AudioLine(List`1 audioStreamDatas) in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\Application\AudioManager.cs:line 106
   at AdobeConnectDownloader.Application.AudioManager.MatchAllAudio(List`1 audioStreamDatas, String fileName, String dataFolderPath, String outputFileFolder, String ffmpegAddress) in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\Application\AudioManager.cs:line 23
   at AdobeConnectDownloader.UI.ProcessForm.<MergeAllFiles>b__79_0() in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 262
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at AdobeConnectDownloader.UI.ProcessForm.MergeAllFiles() in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 170
   at AdobeConnectDownloader.UI.ProcessForm.WebManager_DownloadFileCompleted(Object sender, AsyncCompletedEventArgs e) in C:\My Project\Programing\WinForms\C#\AdobeConnectDownloader\AdobeConnectDownloader\UI\ProcessForm.cs:line 157
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
   at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```

**Comment by HosseinShams00** [comment]
Hello, thank you for using this program
If possible, send the zip file of your meeting so I can check it
@mrMuppet

**Comment by mrMuppet** [comment]
Thank you for offering this software! 
Here you find my file.
[p130t2nzlstv.zip](https://github.com/HosseinShams00/AdobeConnectDownloader/files/13997385/p130t2nzlstv.zip)

**Comment by HosseinShams00** [comment]
Do you have any problem when you watch this meeting online? When I checked your files, the files have problems and no audio files are found in this zip file
@mrMuppet

**Comment by mrMuppet** [comment]
its the file your program downloaded. No, everything works without problems in the stream.

**Comment by HosseinShams00** [comment]
Hello @mrMuppet 
I am sorry for the late reply, unfortunately I am very busy.
Regarding your files, I must state that in the downloaded file related to adobe connect, the audio files related to the microphone and even the images of the cameras start with the cameraVoip prefix and the image files start with the screenshare prefix and according to a series of timings. They start playing in the program and the program I wrote combines these files through ffmpeg.
Now, if you cannot play these files with a player and it gives an error, it is likely that ffmpeg will suffer from this problem and the program not working properly is related to this issue.
I will check your files more in the future and let you know if I find a solution.

**Comment by yavari-alireza** [comment]
I had the same error (Index out of range ..) after some debugging I found the issue is in:
ProcessForm when 
xmlFileData = string.Empty;
and in method DownloadAssetsMethod2(), xmlFileData.IndexOf throws exception

**Comment by mjasnaashari** [comment]
من هم دقیقا همچین مشکلی رو دارم...
![Screenshot 2024-04-07 051552](https://github.com/HosseinShams00/AdobeConnectDownloader/assets/97561345/8cc2f800-49ac-466f-b022-313843062a3f)

**Comment by HosseinShams00** [comment]
Hello @yavari-alireza
thank you very much for your attention and your reports.
I have fixed this issue and have published it. You can now download it from the releases page.

**Comment by HosseinShams00** [comment]
سلام @MohammadJavad-AsnaAshari 
مشکل بر طرف شده متاسفم کمی تاخیر داشت چون به شدت درگیر مشکلات شخصی بودم
ممنون از استفاده شما از برنامه 
شما میتونید نسخه اصلاح شده رو از صفحه releases دانلود کنید و ممنون میشم اگر مشکلی دیدید گزارش کنید.

**Comment by mrMuppet** [comment]
I have still the same issue. "Index was out of range. Must be non-negativ and less than the size of the collection. (Parameter 'index')

**Comment by HosseinShams00** [comment]
hi @mrMuppet 
please send again your error

**Comment by HosseinShams00** [comment]
hi @mrMuppet 
Hello, I checked your problem and the only answer I found that may have happened is that the person creating the meeting may not have recorded the meeting, so make sure that the meeting recording button is pressed.
